name: sparse checkout
description: do sparse checkout
inputs:
  directory:
    description: specify checkout directory
    required: true
  depth:
    description: depth
    required: false
    default: '1'
  token:
    description: github token
    required: true
runs:
  using: composite
  steps:
    - name: sparse checkout
      shell: bash
      run: |
        git clone --filter=blob:none --no-checkout --depth ${{ inputs.depth }} --sparse https://${GITHUB_ACTOR}:${{ inputs.token }}@github.com/${GITHUB_REPOSITORY}.git .
        git sparse-checkout init --cone
        git sparse-checkout add ${{ inputs.directory }}
        git checkout ${GITHUB_SHA}
